const data=[
    {
        id:1,
        Name:"Varun",
        Age:"20",
        Location:"chennai",
        Contact:"9876567890"
    },
    {
        id:2,
        Name:"Nilan",
        Age:"28",
        Location:"chennai",
        Contact:"9876534890"
    },
    {
        id:3,
        Name:"Nivin",
        Age:"10",
        Location:"chennai",
        Contact:"9872567890"
    },
    {
        id:4,
        Name:"Karthick",
        Age:"30",
        Location:"chennai",
        Contact:"987067890"
    }
]
export default data;